name: Spring Boot CD

on:
  workflow_run:
    workflows:
      - "Spring Boot CI"
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull "${{ secrets.DOCKER_IMAGE }}"
            docker stop "${{ secrets.DOCKER_CONTAINER }}" || true # || true는 컨테이너가 없어서 에러가 나더라도 괜찮으니까 그냥 다음으로 넘어가!"라고 명령하는 것
            docker rm "${{ secrets.DOCKER_CONTAINER }}" || true
            docker run -d \
              --name "${{ secrets.DOCKER_CONTAINER }}" \
              -p 80:9000 \
              "${{ secrets.DOCKER_IMAGE }}"